source "https://rubygems.org"

ruby "3.2.3"

gem "roda", "~> 3.79"
gem "puma", "~> 6.4"
gem "redis", "~> 5.2"
gem "racecar", "~> 2.12"
gem "dotenv", "~> 3.1"
gem "json", "~> 2.7"
gem "rdkafka", "~> 0.19"
gem "opentelemetry-sdk", "~> 1.4"
gem "opentelemetry-exporter-otlp", "~> 0.29"
gem "opentelemetry-semantic_conventions", "~> 1.10"

group :development, :test do
  gem "rspec", "~> 3.13"
  gem "rack-test", "~> 2.1"
end
